import img1 from '../img/jumia images/mens-breathable-shoe.jpg';
import img2 from '../img/jumia images/mens-black-leather.jpg';
import img3 from '../img/jumia images/verrati.jpg';
import img4 from '../img/jumia images/verrati-patent.jpg';
import img5 from '../img/jumia images/casual-footwear.jpg';
import img6 from '../img/jumia images/clarks-classic.jpg';
import img7 from '../img/jumia images/mens-formal-leather.jpg';
import img8 from '../img/jumia images/clark-smart.jpg';
import img9 from '../img/jumia images/clark-smart-brown.jpg';
import img10 from '../img/jumia images/kingscartel.jpg';
import img11 from '../img/jumia images/males-half-cover.jpg';
import img12 from '../img/jumia images/clarke.jpg';
import img13 from '../img/jumia images/sneakers.jpg';
import img14 from '../img/jumia images/camel-sandal.jpg';
import img15 from '../img/jumia images/cross-palm.jpg';
import img16 from '../img/jumia images/sleak-comfy.jpg';
import img17 from '../img/jumia images/men-casual-palm.jpg';
import img18 from '../img/jumia images/aligator-loafers.jpg';
import img19 from '../img/jumia images/unisex-water-shoes.jpg';
import img20 from '../img/jumia images/velcro-fuse.jpg';
import img21 from '../img/jumia images/men-formal-slip on.jpg';
import img22 from '../img/jumia images/men-half-cover shoe.jpg';
import img23 from '../img/jumia images/alien.jpg';
import img24 from '../img/jumia images/camel-sandal.jpg';
import img25 from '../img/jumia images/leatherr.jpg';
import img26 from '../img/jumia images/men-leather-palm-slippers.jpg';
import img27 from '../img/jumia images/simple-rope-palm.jpg';
import img28 from '../img/jumia images/male-coven-half-cover.jpg';
// function discountCalc(price, discount){
//     return ((100 - discount) / 100) * price
// }
const ProductsInfo =[
    {id: 1,
        name: 'Men Breathable Mesh Sneakers',
        price: 2900,
        discount: 46,
        color: 'black',
        stars: 4,
        image: img1,
        freeDelivery: true,
    },
    {id:2,
        name: 'Men Black Leather Palm',
        price: 3815,
        discount: 62,
        color: 'black',
        stars: 4,
        image: img2,
    },
    {id:3,
        name: 'Verrati Suede Leather',
        price: 10300,
        discount: 66,
        color: 'brown',
        stars: 3,
        image: img3,
    },
    {id:4,
        name: `Verrati men's Patent Leather`,
        price: 75999,
        discount: 73,
        color: 'black',
        stars: 4,
        image: img4,
        freeDelivery: true,
    },
    {id:5,
        name: 'Casual Sneaker Fashion Footwear ',
        price: 10000,
        discount: 21,
        color: 'white',
        stars: 4,
        image: img5,
    },
    {id:6,
        name: `Clarks Classic Men Half Shoe`,
        price: 8500,
        discount: 59,
        color: null,
        stars: 4,
        image: img6
    },
    {id:7,
        name: 'Men Formal Shoe Handmade',
        price: 10364,
        discount: 52,
        color: 'black',
        stars: 4,
        image: img7
    },
    {id:8,
        name: `Clarks Men Smart Casual Loafers`,
        price: 13750,
        discount: 19,
        color: 'black',
        stars: 4,
        image: img8,
    },
    {id:9,
        name: `Clarks Smart Brown`,
        price: 22900,
        discount: 19,
        color: 'brown',
        stars: 4,
        image: img9,
    },
    {id:10,
        name: `Kingskartel Slide Panther Slide`,
        price: 4999,
        discount: 50,
        color: 'black',
        stars: 3,
        image: img10,
    },
    {id:11,
        name: `Male Half Cover Leather Shoe`,
        price: 29000,
        discount: 17,
        color: 'black',
        stars: 4,
        image: img11,
        freeDelivery: true,
    },
    {id:12,
        name: `Classic Clarks Men Loafers`,
        price: 13500,
        discount: 45,
        color: 'black',
        stars: 4,
        image: img12,
    },
    {id:13,
        name: 'Men abd Ladies Sports Breathable Sneakers',
        price: 5500,
        discount: 31,
        color: 'black',
        stars: 4,
        image: img13,
        freeDelivery: true,
    },
    {id:14,
        name: `Men's Casual Sports Sandals`,
        price: 13800,
        discount: 58,
        color: 'black',
        stars: 4,
        image: img14,
    },
    {id:15,
        name: 'Men Cross Palm',
        price: 7500,
        discount: 16,
        color: 'black',
        stars: 3,
        image: img15,
    },
    {id:16,
        name: 'Sleek Fashion Comfy Sneakers',
        price: 5999,
        discount: 50,
        color: null,
        stars: 4,
        image: img16,
        freeDelivery: true,
    },
    {id:17,
        name: 'Men Casual Slides',
        price: 10500,
        discount: 28,
        color: null,
        stars: 3,
        image: img17,
    },
    {id:18,
        name: 'Men Formal Shoes Alligator',
        price: 12350,
        discount: 49,
        color: 'brown',
        stars: 4,
        image: img18,
    },
    {id:19,
        name: 'Unisex Water Shoe Outdoor',
        price: 10925,
        discount: 16,
        color: null,
        stars: 4,
        image: img19,
        freeDelivery: true,
    },
    {id:20,
        name: 'Trekkers Unisex Shoe',
        price: 3900,
        discount: 50,
        color: null,
        stars: 4,
        image: img20,
    },
    {id:21,
        name: `Men Business Footwear`,
        price: 10869,
        discount: 49,
        color: 'black',
        stars: 4,
        image: img21
    },
    {id:22,
        name: 'Men Half Cover Leather Shoe',
        price: 29000,
        discount: 17,
        color: 'dark brown',
        stars: 4,
        image: img22,
    },
    {id:23,
        name:  `Clarks Smart Men's Spin-on`,
        price: 19000,
        discount: 5,
        color: 'black',
        stars: 3,
        image: img23,
    },
    {id:24,
        name: 'Camel Fashion Sandals',
        price: 15699,
        discount: 31,
        color: 'dark brown',
        stars: 4,
        image: img24,
        freeDelivery: true,
    },
    {id:25,
        name: 'Loafers Slip-on High Quality',
        price: 12540,
        discount: 23,
        color: 'dark brown',
        stars: 3,
        image: img25,
        freeDelivery: true,
    },
    {id:26,
        name: 'Men Leather Palm Slippers',
        price: 4950,
        discount: 24,
        color: 'black',
        stars: 4,
        image: img26
    },
    {id:27,
        name: 'Men Simple Palm Rope',
        price: 4300,
        discount: 48,
        color: 'black',
        stars: 4,
        image: img27
    },
    {id:28,
        name: 'Men Half Cover Woven Leather ',
        price: 17000,
        discount: 17,
        color: 'black',
        stars: 4,
        image: img28
    },

]

export default ProductsInfo